
SRCS_TINYXML = lib/tinyxml2/tinyxml2.cpp

SRCS_INDEXTREE = lib/indextree/IndexTree.cpp  \
                 lib/indextree/IndexTreeWriter.cpp \
                 lib/indextree/IndexTreeHelper.cpp                         


