# vim: set sts=4 expandtab:
IM_CONFIG_SHORT="$(gettext "AlphaIM")"

IM_CONFIG_LONG="$(gettext "AlphaIM input method
 * Required for all: alphaim
 * Application platform support:
   * XIM: built-in XIM server
   * GTK: alphaim GTK input method module
   * Qt: alphaim Qt platform input context plugin")"

package_auto () {
    package_status alphaim
}

package_menu () {
    package_status alphaim
}
