/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -N -p qaiminputcontextproxy -c QAimInputContextProxy interfaces/org.freedesktop.AlphaIM.InputContext.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef QAIMINPUTCONTEXTPROXY_H
#define QAIMINPUTCONTEXTPROXY_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.AlphaIM.InputContext
 */
class QAimInputContextProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.AlphaIM.InputContext"; }

public:
    QAimInputContextProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~QAimInputContextProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> Destroy(uint ic)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic);
        return asyncCallWithArgumentList(QStringLiteral("Destroy"), argumentList);
    }

    inline QDBusPendingReply<int> Disable(uint ic)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic);
        return asyncCallWithArgumentList(QStringLiteral("Disable"), argumentList);
    }

    inline QDBusPendingReply<int> Enable(uint ic)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic);
        return asyncCallWithArgumentList(QStringLiteral("Enable"), argumentList);
    }

    inline QDBusPendingReply<int> FocusIn(uint id)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(id);
        return asyncCallWithArgumentList(QStringLiteral("FocusIn"), argumentList);
    }

    inline QDBusPendingReply<int> FocusOut(uint ic)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic);
        return asyncCallWithArgumentList(QStringLiteral("FocusOut"), argumentList);
    }

    inline QDBusPendingReply<bool> IsEnabled(uint ic)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic);
        return asyncCallWithArgumentList(QStringLiteral("IsEnabled"), argumentList);
    }

    inline QDBusPendingReply<int> ProcessKeyEvent(uint ic, uint keyval, uint keycode, uint state)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic) << QVariant::fromValue(keyval) << QVariant::fromValue(keycode) << QVariant::fromValue(state);
        return asyncCallWithArgumentList(QStringLiteral("ProcessKeyEvent"), argumentList);
    }

    inline QDBusPendingReply<int> PropertyActivate(uint ic, const QString &name, int state)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic) << QVariant::fromValue(name) << QVariant::fromValue(state);
        return asyncCallWithArgumentList(QStringLiteral("PropertyActivate"), argumentList);
    }

    inline QDBusPendingReply<int> Reset(uint ic)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic);
        return asyncCallWithArgumentList(QStringLiteral("Reset"), argumentList);
    }

    inline QDBusPendingReply<int> SetCapabilities(uint ic, uint caps)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic) << QVariant::fromValue(caps);
        return asyncCallWithArgumentList(QStringLiteral("SetCapabilities"), argumentList);
    }

    inline QDBusPendingReply<int> SetCursorLocation(uint ic, int x, int y, int w, int h)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic) << QVariant::fromValue(x) << QVariant::fromValue(y) << QVariant::fromValue(w) << QVariant::fromValue(h);
        return asyncCallWithArgumentList(QStringLiteral("SetCursorLocation"), argumentList);
    }

    inline QDBusPendingReply<int> SetSurroundingText(uint ic, const QDBusVariant &text, uint cursor_pos, uint anchor_pos)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(ic) << QVariant::fromValue(text) << QVariant::fromValue(cursor_pos) << QVariant::fromValue(anchor_pos);
        return asyncCallWithArgumentList(QStringLiteral("SetSurroundingText"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void CommitText(const QString &text);
};

#endif
